url: http://jsonapi.org

lsi: false
source: .
destination: ./public
exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - ./public
  - ./stylesheets/*.scss
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
highlighter: pygments
port: 9876

collections:
  format:
    output: true

defaults:
  - scope:
      path: ""
      type: format
    values:
      layout: page
      show_sidebar: true
      is_spec_page: true

latest_version: 1.0


# `safe `must be set false for jekyll-redirect-from
# to run in development. (Github Pages will override
# `safe` to be true on deploy, but it makes an
# exception for jekyll-redirect from.)
safe: false
gems:
  - jekyll-redirect-from

navigation:
- title: JSON API
  url: /
- title: Specification
  url: /format/
- title: Extensions
  url: /extensions/
- title: Recommendations
  url: /recommendations/
- title: Examples
  url: /examples/
- title: Implementations
  url: /implementations/
- title: FAQ
  url: /faq/
- title: About
  url: /about/

quicklinks:
- title: View the specification
  url: /format/
- title: Contribute on GitHub
  url: https://github.com/json-api/json-api
